before_script:
  - '[ "$CI_PIPELINE_SOURCE" == "external_pull_request_event" ] && export OOD_PACKAGING_BUILD_BOX_VERSION=latest'
  - docker info
  - '[ -d tmp ] || mkdir tmp'
  - bundle install --path vendor/bundle

stages:
  - image
  - build
  - deploy

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 0
  OOD_BUILD_REPO: '4.1'
  OOD_PACKAGING_DEBUG: 'true'
  OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand-sha512.sec
  OOD_PACKAGING_GPG_PASSPHRASE: /systems/osc_certs/gpg/ondemand/.gpgpass

build-image:
  stage: image
  rules:
    # Re-enable once Gitlab instance using plugin to integrate with Github
    # - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event"'
    - if: '$CI_COMMIT_BRANCH !~ /^(main|[0-9]\.[0-9])$/ && $CI_COMMIT_TAG == null'
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /v[0-9].+/
  script:
    - 'bundle exec rake ood_packaging:buildbox:pull || true'
    - bundle exec rake ood_packaging:buildbox:build
  parallel:
    matrix:
      - OOD_PACKAGING_DIST: [el8]
        OOD_PACKAGING_ARCH: [x86_64, aarch64, ppc64le]
        OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand.sec
      - OOD_PACKAGING_DIST: [el9]
        OOD_PACKAGING_ARCH: [x86_64, aarch64, ppc64le]
      - OOD_PACKAGING_DIST: [ubuntu-22.04, ubuntu-24.04, debian-12]
        OOD_PACKAGING_ARCH: [x86_64, aarch64]
      - OOD_PACKAGING_DIST: [amzn2023]
        OOD_PACKAGING_ARCH: [x86_64, aarch64]

build-ondemand-release:
  stage: build
  rules:
    # Re-enable once Gitlab instance using plugin to integrate with Github
    # - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event"'
    - if: '$CI_COMMIT_BRANCH !~ /^(main|[0-9]\.[0-9])$/ && $CI_COMMIT_TAG == null'
    - if: '$CI_COMMIT_TAG =~ /^ondemand-release-[0-9]/'
  script:
    - bundle exec rake ood_packaging:package:ondemand-release
  parallel:
    matrix:
      - OOD_PACKAGING_DIST: [el8]
        OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand.sec
      - OOD_PACKAGING_DIST: [el9, amzn2023]
      - OOD_PACKAGING_DIST: [ubuntu-22.04, ubuntu-24.04]
      - OOD_PACKAGING_DIST: [debian-12]
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

build-ondemand-release-latest:
  stage: build
  rules:
    # Re-enable once Gitlab instance using plugin to integrate with Github
    # - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event"'
    - if: '$CI_COMMIT_BRANCH !~ /^(main|[0-9]\.[0-9])$/ && $CI_COMMIT_TAG == null'
    - if: '$CI_COMMIT_TAG =~ /^ondemand-release-latest-/'
  script:
    - bundle exec rake ood_packaging:package:ondemand-release-latest
  parallel:
    matrix:
      - OOD_PACKAGING_DIST: [el8]
        OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand.sec
      - OOD_PACKAGING_DIST: [el9, amzn2023]
      - OOD_PACKAGING_DIST: [ubuntu-22.04, ubuntu-24.04]
      - OOD_PACKAGING_DIST: [debian-12]
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

build-ondemand-runtime:
  stage: build
  rules:
    # Re-enable once Gitlab instance using plugin to integrate with Github
    # - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event"'
    - if: '$CI_COMMIT_BRANCH !~ /^(main|[0-9]\.[0-9])$/ && $CI_COMMIT_TAG == null'
    - if: '$CI_COMMIT_TAG =~ /^ondemand-runtime-/'
  script:
    - bundle exec rake ood_packaging:package:ondemand-runtime
  parallel:
    matrix:
      - OOD_PACKAGING_DIST: [el8]
        OOD_PACKAGING_ARCH: [x86_64, aarch64, ppc64le]
        OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand.sec
      - OOD_PACKAGING_DIST: [el9]
        OOD_PACKAGING_ARCH: [x86_64, aarch64, ppc64le]
      - OOD_PACKAGING_DIST: [el9, amzn2023]
        OOD_PACKAGING_ARCH: [x86_64, aarch64]
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

build-scl-utils:
  stage: build
  rules:
    # Re-enable once Gitlab instance using plugin to integrate with Github
    # - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event"'
    - if: '$CI_COMMIT_BRANCH !~ /^(main|[0-9]\.[0-9])$/ && $CI_COMMIT_TAG == null'
    - if: '$CI_COMMIT_TAG =~ /^scl-utils-/'
  script:
    - bundle exec rake ood_packaging:package:scl-utils[$DIST]
  parallel:
    matrix:
      - OOD_PACKAGING_DIST: [amzn2023]
        OOD_PACKAGING_ARCH: [x86_64, aarch64]
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

build-passenger:
  stage: build
  rules:
    # Re-enable once Gitlab instance using plugin to integrate with Github
    # - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event"'
    - if: '$CI_COMMIT_BRANCH !~ /^(main|[0-9]\.[0-9])$/ && $CI_COMMIT_TAG == null'
    - if: '$CI_COMMIT_TAG =~ /^passenger-/'
  script:
    - bundle exec rake ood_packaging:package:passenger[$DIST]
  parallel:
    matrix:
      - OOD_PACKAGING_DIST: [el8]
        OOD_PACKAGING_ARCH: [x86_64, aarch64, ppc64le]
        OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand.sec
      - OOD_PACKAGING_DIST: [el9]
        OOD_PACKAGING_ARCH: [x86_64, aarch64, ppc64le]
      - OOD_PACKAGING_DIST: [ubuntu-22.04, ubuntu-24.04, debian-12]
        OOD_PACKAGING_ARCH: [x86_64, aarch64]
      - OOD_PACKAGING_DIST: [amzn2023]
        # Amazon aarch64 takes hours so build by hand for now
        # OOD_PACKAGING_ARCH: [x86_64, aarch64]
        OOD_PACKAGING_ARCH: [x86_64]
  timeout: 3h
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

build-ondemand_exporter:
  stage: build
  rules:
    # Re-enable once Gitlab instance using plugin to integrate with Github
    # - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event"'
    - if: '$CI_COMMIT_BRANCH !~ /^(main|[0-9]\.[0-9])$/ && $CI_COMMIT_TAG == null'
    - if: '$CI_COMMIT_TAG =~ /^ondemand_exporter-/'
  script:
    - bundle exec rake ood_packaging:package:ondemand_exporter[$DIST]
  parallel:
    matrix:
      - OOD_PACKAGING_DIST: [el8]
        OOD_PACKAGING_ARCH: [x86_64, aarch64, ppc64le]
        OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand.sec
      - OOD_PACKAGING_DIST: [el9]
        OOD_PACKAGING_ARCH: [x86_64, aarch64, ppc64le]
      - OOD_PACKAGING_DIST: [amzn2023]
        OOD_PACKAGING_ARCH: [x86_64, aarch64]
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

build-ondemand-compute:
  stage: build
  rules:
    # Re-enable once Gitlab instance using plugin to integrate with Github
    # - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event"'
    - if: '$CI_COMMIT_BRANCH !~ /^(main|[0-9]\.[0-9])$/ && $CI_COMMIT_TAG == null'
    - if: '$CI_COMMIT_TAG =~ /^ondemand-compute-/'
  script:
    - bundle exec rake ood_packaging:package:ondemand-compute[$DIST]
    - cp -r tmp/output/$OOD_PACKAGING_DIST-x86_64 tmp/output/$OOD_PACKAGING_DIST-aarch64
    - cp -r tmp/output/$OOD_PACKAGING_DIST-x86_64 tmp/output/$OOD_PACKAGING_DIST-ppc64le
  parallel:
    matrix:
      - OOD_PACKAGING_DIST: [el8]
        OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand.sec
      - OOD_PACKAGING_DIST: [el9, amzn2023]
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

build-python-websockify:
  stage: build
  rules:
    # Re-enable once Gitlab instance using plugin to integrate with Github
    # - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event"'
    - if: '$CI_COMMIT_BRANCH !~ /^(main|[0-9]\.[0-9])$/ && $CI_COMMIT_TAG == null'
    - if: '$CI_COMMIT_TAG =~ /^python-websockify-/'
  script:
    - bundle exec rake ood_packaging:package:python-websockify[$DIST]
  parallel:
    matrix:
      - OOD_PACKAGING_DIST: [el8]
        OOD_PACKAGING_ARCH: [x86_64, aarch64, ppc64le]
        OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand.sec
      - OOD_PACKAGING_DIST: [el9]
        OOD_PACKAGING_ARCH: [x86_64, aarch64, ppc64le]
      - OOD_PACKAGING_DIST: [amzn2023]
        OOD_PACKAGING_ARCH: [x86_64, aarch64]
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

build-turbovnc:
  stage: build
  rules:
    # Re-enable once Gitlab instance using plugin to integrate with Github
    # - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event"'
    - if: '$CI_COMMIT_BRANCH !~ /^(main|[0-9]\.[0-9])$/ && $CI_COMMIT_TAG == null'
    - if: '$CI_COMMIT_TAG =~ /^turbovnc-/'
  script:
    - bundle exec rake ood_packaging:package:turbovnc
  parallel:
    matrix:
      - OOD_PACKAGING_DIST: [el8]
        OOD_PACKAGING_ARCH: [x86_64, aarch64, ppc64le]
        OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand.sec
      - OOD_PACKAGING_DIST: [el9]
        OOD_PACKAGING_ARCH: [x86_64, aarch64, ppc64le]
      - OOD_PACKAGING_DIST: [amzn2023]
        OOD_PACKAGING_ARCH: [x86_64, aarch64]
  timeout: 3h
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

package-deploy-latest:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /v[0-9].+/ && $CI_COMMIT_TAG !~ /ondemand-release|turbovnc|python-websockify|ondemand-compute/
  script:
    - ./release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c main ./tmp/output/*

package-deploy-staging:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /v[0-9].+/ && $CI_COMMIT_TAG !~ /ondemand-release|turbovnc|python-websockify|ondemand-compute/
  script:
    - ./release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c staging -r $OOD_BUILD_REPO ./tmp/output/*

package-deploy-release:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^ondemand-release/'
  script:
    - ./release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c release ./tmp/output/*

package-deploy-latest-compute:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^turbovnc-/'
    - if: '$CI_COMMIT_TAG =~ /^python-websockify-/'
    - if: '$CI_COMMIT_TAG =~ /^ondemand-compute-/'
  script:
    - ./release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c compute ./tmp/output/*

package-deploy-staging-compute:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^turbovnc-/'
    - if: '$CI_COMMIT_TAG =~ /^python-websockify-/'
    - if: '$CI_COMMIT_TAG =~ /^ondemand-compute-/'
  script:
    - ./release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c staging-compute -r $OOD_BUILD_REPO ./tmp/output/*

package-deploy-build:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^ondemand-runtime-/'
    - if: '$CI_COMMIT_TAG =~ /^scl-utils-/'
    - if: '$CI_COMMIT_TAG =~ /^passenger-/'
  script:
    - ./release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c build -r $OOD_BUILD_REPO ./tmp/output/*
