FROM centos:8

# install all the dependencies
RUN dnf -y update 
RUN dnf install -y dnf-utils 
RUN dnf config-manager --set-enabled powertools
RUN dnf -y module enable nodejs:12 ruby:2.7
RUN dnf install -y \
        make gcc gcc-c++ git rsync rpm-build redhat-rpm-config
RUN dnf install -y libselinux libselinux-devel
RUN dnf install -y selinux-policy selinux-policy-devel
RUN dnf install -y scl-utils

RUN dnf install -y https://yum.osc.edu/ondemand/latest/ondemand-release-web-latest-1-6.noarch.rpm
RUN dnf install -y \
        ondemand-runtime ondemand-scldevel ondemand-build ondemand-ruby ondemand-python ondemand-nodejs 

RUN dnf clean all && rm -rf /var/cache/dnf/*

RUN groupadd <%= ctr_user %> && \
    useradd --create-home --gid <%= ctr_user %> <%= ctr_user %>
