FROM <%= base_image %>
MAINTAINER Trey Dockendorf <tdockendorf@osc.edu>
ENV LANG=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
ENV GEM_PATH=<%= ctr_gems_dir %>:
<% if dist == 'el7' -%>
RUN yum update -y && yum clean all && rm -rf /var/cache/yum/*
RUN yum install -y yum-utils epel-release centos-release-scl && yum clean all && rm -rf /var/cache/yum/*
RUN yum install -y <%= scl_ruby %>-ruby sudo which wget @buildsys-build \
    rpm-build rpmdevtools rpm-sign scl-utils-build && \
    yum clean all && rm -rf /var/cache/yum/*
<% elsif dist =~ /^el/ -%>
RUN dnf update -y && dnf clean all && rm -rf /var/cache/dnf/*
RUN dnf install -y dnf-utils epel-release langpacks-en glibc-all-langpacks && dnf clean all && rm -rf /var/cache/dnf/*
RUN dnf config-manager --set-enabled powertools && dnf clean all && rm -rf /var/cache/dnf/*
RUN dnf module enable -y ruby:<%= ruby_version %> && dnf clean all && rm -rf /var/cache/dnf/*
RUN dnf module enable -y nodejs:<%= nodejs_version %> && dnf clean all && rm -rf /var/cache/dnf/*
RUN dnf install -y ruby sudo which wget \
    gcc-c++ gcc make patch \
    rpm-build rpmdevtools rpm-sign scl-utils-build && \
    dnf clean all && rm -rf /var/cache/dnf/*
<% elsif dist =~ /^ubuntu|debian/ -%>
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -y && apt install -y gpg apt-transport-https ca-certificates && apt clean all -y
RUN echo "deb [arch=amd64] https://apt.osc.edu/ondemand/build/<%= ondemand_repo_version %>/web/apt <%= codename %> main" > /etc/apt/sources.list.d/ondemand-web.list
COPY RPM-GPG-KEY-ondemand /build/RPM-GPG-KEY-ondemand
RUN cat /build/RPM-GPG-KEY-ondemand | gpg --dearmor > /etc/apt/trusted.gpg.d/ondemand-web.gpg
RUN apt update -y && apt upgrade -y && apt clean all -y
RUN apt update -y && apt install -y locales && locale-gen $LANG && \
    apt clean all -y
RUN apt update -y && apt install -y \
    init debhelper devscripts dh-make build-essential lintian equivs \
    sudo rake wget curl ruby bundler && \
    apt clean all -y
RUN echo "deb https://deb.nodesource.com/node_<%= nodejs_version %>.x <%= codename %> main" > /etc/apt/sources.list.d/nodesource.list
RUN curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor > /etc/apt/trusted.gpg.d/nodesource.gpg
<% end -%>
COPY . /build
RUN /bin/bash /build/install.sh
