FROM <%= base_image %>
MAINTAINER Trey Dockendorf <tdockendorf@osc.edu>
ENV LANG=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
<% if dist == 'el7' -%>
RUN yum update -y && yum clean all && rm -rf /var/cache/yum/*
RUN yum install -y yum-utils epel-release centos-release-scl && yum clean all && rm -rf /var/cache/yum/*
RUN yum install -y rh-ruby27-ruby sudo which wget \
    rpm-build rpmdevtools rpm-sign scl-utils-build && \
    yum clean all && rm -rf /var/cache/yum/*
RUN yum install -y <%= ondemand_repo_url %> && \
    sed -i 's|/latest/|<%= ondemand_build_repo %>|g' /etc/yum.repos.d/ondemand-web.repo && \
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-ondemand && \
    yum clean all && rm -rf /var/cache/yum/*
<% elsif dist =~ /^el/ -%>
RUN dnf update -y && dnf clean all && rm -rf /var/cache/dnf/*
RUN dnf install -y dnf-utils epel-release langpacks-en glibc-all-langpacks && dnf clean all && rm -rf /var/cache/dnf/*
RUN dnf config-manager --set-enabled powertools && dnf clean all && rm -rf /var/cache/dnf/*
RUN dnf module enable -y ruby:2.7 && dnf clean all && rm -rf /var/cache/dnf/*
RUN dnf install -y ruby sudo which wget \
    rpm-build rpmdevtools rpm-sign scl-utils-build && \
    dnf clean all && rm -rf /var/cache/dnf/*
RUN dnf install -y <%= ondemand_repo_url %> && \
    sed -i 's|/latest/|<%= ondemand_build_repo %>|g' /etc/yum.repos.d/ondemand-web.repo && \
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-ondemand && \
    dnf clean all && rm -rf /var/cache/dnf/*
<% elsif dist =~ /^ubuntu|debian/ -%>
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -y && apt upgrade -y && apt clean all -y
RUN apt update -y && apt install -y locales && locale-gen $LANG && \
    apt clean all -y
RUN apt update -y && apt install -y init debhelper devscripts dh-make build-essential lintian equivs \
    sudo rake wget curl ruby && \
    ln -snf /bin/bundle2.7 /bin/bundle && \
    apt clean all -y
RUN wget -O /tmp/ondemand-release-web.deb <%= ondemand_repo_url %> && \
    apt update -y && apt install -y /tmp/ondemand-release-web.deb && rm -f /tmp/ondemand-release-web.deb && \
    sed -i 's|/latest/|<%= ondemand_build_repo %>|g' /etc/apt/sources.list.d/ondemand-web.list && \
    apt update -y && \
    apt clean all -y
<% end -%>
COPY . /build
RUN /bin/bash /build/install.sh
